server:
  port: 9001
spring:
  application:
    name: community-base

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.29.170:3306/community_base?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.29.125:6868/eureka
  instance:
    prefer-ip-address: true

rabbitmq:
  host:
    192.168.29.170
