server:
  port: 9006

spring:
  application:
    name: community-comment

  data:
    mongodb:
      host: 192.168.29.178
      database: community_comment
  redis:
    host: 192.168.29.178

eureka:
  client:
    service-url:
      defaultZone: http://192.168.29.125:6868/eureka
  instance:
    prefer-ip-address: true

