
spring:
  application:
    name: community-eureka
  rabbitmq:
    host: 192.168.29.170   

server:
  port: 6868
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.29.125:${server.port}/eureka


