host: 192.168.29.170

server:
  port: 9004
spring:
  application:
    name: community-friend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}/community_user
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
jwt:
  config:
    key: itcast
    duration: 1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.29.125:6868/eureka
  instance:
    prefer-ip-address: true
s
